ip: 192.168.0.99
accounts:
  - username: admin
    password: admin123
  - username: scott
    password: scott123
  - username: stan
    password: stan1996
  - username: cxv
    password: cxv123

admin_test:
  project_config:
    project_path: project/admin_test
    bin_path: project/admin_test/bin
    git_url: http://192.168.0.13/platform/soga_admin
  client_config:
    host: 192.168.0.30
    port: 22
    user: root
    password: admin@123
  git_config:
    user_name: bin.peng
    pass_word: pb123654
  build_configs:
    - env: admin
      mod_path: project/admin_test
      bin_name: bin/soga_admin
      name: soga_admin
  zip_file_path: bin/admin_server.zip
  zip_name: admin_server.zip
  server_path: /root/soga/soga_im_admin_server

admin_release:
  project_config:
    project_path: project/admin_release
    bin_path: project/admin_release/bin
    git_url: http://192.168.0.13/platform/soga_admin
  client_config:
    host: 192.168.0.30
    port: 22
    user: root
    password: admin@123
  git_config:
    user_name: bin.peng
    pass_word: pb123654
  build_configs:
    - env: admin
      mod_path: project/admin_release
      bin_name: bin/soga_admin
      name: soga_admin
  zip_file_path: bin/admin_server.zip
  zip_name: admin_server.zip
  server_path: /root/soga_admin_server

im_enterprise_test:
  zip_file_path: bin/im_enterprise.zip
  zip_name: im_enterprise.zip
  server_path: /root/soga/soga_im_enterprise/bin
  project_config:
    project_path: project/im_enterprise_test
    bin_path: project/im_enterprise_test/bin
    git_url: http://192.168.0.13/server/soga_im_enterprise
  client_config:
    host: 192.168.0.30
    port: 22
    user: root
    password: admin@123
  git_config:
    user_name: bin.peng
    pass_word: pb123654
  build_configs:
    - env: soga_api_chat
      mod_path: project/im_enterprise_test/cmd/api/chat
      bin_name: bin/soga_api_chat
      name: soga_api_chat
    - env: soga_api_chatroom
      mod_path: project/im_enterprise_test/cmd/api/chatroom
      bin_name: bin/soga_api_chatroom
      name: soga_api_chatroom
    - env: soga_rpc_chat
      mod_path: project/im_enterprise_test/cmd/rpc/chat
      bin_name: bin/soga_rpc_chat
      name: soga_rpc_chat
    - env: soga_rpc_game
      mod_path: project/im_enterprise_test/cmd/rpc/game
      bin_name: bin/soga_rpc_game
      name: soga_rpc_game
    - env: soga_cron
      mod_path: project/im_enterprise_test/cmd/cron
      bin_name: bin/soga_cron
      bin: soga_cron
      name: soga_cron
    - env: soga_tool
      mod_path: project/im_enterprise_test/cmd/tool
      bin_name: bin/soga_tool
      bin: soga_tool
      name: soga_tool

im_enterprise_release:
  zip_file_path: bin/im_enterprise.zip
  zip_name: im_enterprise.zip
  server_path: /root/soga/soga_im_enterprise/bin
  project_config:
    project_path: project/im_enterprise_release
    bin_path: project/im_enterprise_release/bin
    git_url: http://192.168.0.13/server/soga_im_enterprise
  client_config:
    host: 192.168.0.30
    port: 22
    user: root
    password: admin@123
  git_config:
    user_name: bin.peng
    pass_word: pb123654
  build_configs:
    - env: soga_api_chat
      mod_path: project/im_enterprise_release/cmd/api/chat
      bin_name: bin/soga_api_chat
      name: soga_api_chat
    - env: soga_api_chatroom
      mod_path: project/im_enterprise_release/cmd/api/chatroom
      bin_name: bin/soga_api_chatroom
      name: soga_api_chatroom
    - env: soga_rpc_chat
      mod_path: project/im_enterprise_release/cmd/rpc/chat
      bin_name: bin/soga_rpc_chat
      name: soga_rpc_chat
    - env: soga_rpc_game
      mod_path: project/im_enterprise_release/cmd/rpc/game
      bin_name: bin/soga_rpc_game
      name: soga_rpc_game
    - env: soga_cron
      mod_path: project/im_enterprise_release/cmd/cron
      bin_name: bin/soga_cron
      bin: soga_cron
      name: soga_cron
    - env: soga_tool
      mod_path: project/im_enterprise_release/cmd/tool
      bin_name: bin/soga_tool
      bin: soga_tool
      name: soga_tool

im_server_test:
  zip_file_path: bin/im_server.zip
  zip_name: im_server.zip
  server_path: /root/soga/soga_im_server/bin
  project_config:
    project_path: project/im_server_test
    bin_path: project/im_server_test/bin
    git_url: http://192.168.0.13/server/soga_im_server
  client_config:
    host: 192.168.0.30
    port: 22
    user: root
    password: admin@123
  git_config:
    user_name: bin.peng
    pass_word: pb123654
  build_configs:
    - env: soga_im_api
      mod_path: project/im_server_test/cmd/api/soga_im_api
      bin_name: bin/soga_im_api
      name: soga_im_api
    - env: soga_im_msg_gateway
      mod_path: project/im_server_test/cmd/api/soga_im_msg_gateway
      bin_name: bin/soga_im_msg_gateway
      name: soga_im_msg_gateway
    - env: soga_im_msg_transfer
      mod_path: project/im_server_test/cmd/api/soga_im_msg_transfer
      bin_name: bin/soga_im_msg_transfer
      name: soga_im_msg_transfer
    - env: soga_im_push
      mod_path: project/im_server_test/cmd/api/soga_im_push
      bin_name: bin/soga_im_push
      name: soga_im_push
    - env: soga_im_rpc_auth
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_auth
      bin_name: bin/soga_im_rpc_auth
      name: soga_im_rpc_auth
    - env: soga_im_rpc_cache
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_cache
      bin_name: bin/soga_im_rpc_cache
      name: soga_im_rpc_cache
    - env: soga_im_rpc_conversation
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_conversation
      bin_name: bin/soga_im_rpc_conversation
      name: soga_im_rpc_conversation
    - env: soga_im_rpc_friend
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_friend
      bin_name: bin/soga_im_rpc_friend
      name: soga_im_rpc_friend
    - env: soga_im_rpc_group
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_group
      bin_name: bin/soga_im_rpc_group
      name: soga_im_rpc_group
    - env: soga_im_rpc_msg
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_msg
      bin_name: bin/soga_im_rpc_msg
      name: soga_im_rpc_msg
    - env: soga_im_rpc_office
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_office
      bin_name: bin/soga_im_rpc_office
      name: soga_im_rpc_office
    - env: soga_im_rpc_organization
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_organization
      bin_name: bin/soga_im_rpc_organization
      name: soga_im_rpc_organization
    - env: soga_im_rpc_user
      mod_path: project/im_server_test/cmd/rpc/soga_im_rpc_user
      bin_name: bin/soga_im_rpc_user
      name: soga_im_rpc_user

im_server_release:
  zip_file_path: bin/im_server.zip
  zip_name: im_server.zip
  server_path: /root/soga/soga_im_server/bin
  project_config:
    project_path: project/im_server_release
    bin_path: project/im_server_release/bin
    git_url: http://192.168.0.13/server/soga_im_server
  client_config:
    host: 192.168.0.30
    port: 22
    user: root
    password: admin@123
  git_config:
    user_name: bin.peng
    pass_word: pb123654
  build_configs:
    - env: soga_im_api
      mod_path: project/im_server_release/cmd/api/soga_im_api
      bin_name: bin/soga_im_api
      name: soga_im_api
    - env: soga_im_msg_gateway
      mod_path: project/im_server_release/cmd/api/soga_im_msg_gateway
      bin_name: bin/soga_im_msg_gateway
      name: soga_im_msg_gateway
    - env: soga_im_msg_transfer
      mod_path: project/im_server_release/cmd/api/soga_im_msg_transfer
      bin_name: bin/soga_im_msg_transfer
      name: soga_im_msg_transfer
    - env: soga_im_push
      mod_path: project/im_server_release/cmd/api/soga_im_push
      bin_name: bin/soga_im_push
      name: soga_im_push
    - env: soga_im_rpc_auth
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_auth
      bin_name: bin/soga_im_rpc_auth
      name: soga_im_rpc_auth
    - env: soga_im_rpc_cache
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_cache
      bin_name: bin/soga_im_rpc_cache
      name: soga_im_rpc_cache
    - env: soga_im_rpc_conversation
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_conversation
      bin_name: bin/soga_im_rpc_conversation
      name: soga_im_rpc_conversation
    - env: soga_im_rpc_friend
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_friend
      bin_name: bin/soga_im_rpc_friend
      name: soga_im_rpc_friend
    - env: soga_im_rpc_group
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_group
      bin_name: bin/soga_im_rpc_group
      name: soga_im_rpc_group
    - env: soga_im_rpc_msg
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_msg
      bin_name: bin/soga_im_rpc_msg
      name: soga_im_rpc_msg
    - env: soga_im_rpc_office
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_office
      bin_name: bin/soga_im_rpc_office
      name: soga_im_rpc_office
    - env: soga_im_rpc_organization
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_organization
      bin_name: bin/soga_im_rpc_organization
      name: soga_im_rpc_organization
    - env: soga_im_rpc_user
      mod_path: project/im_server_release/cmd/rpc/soga_im_rpc_user
      bin_name: bin/soga_im_rpc_user
      name: soga_im_rpc_user